users:
  - email: abhishek@voltup.in
    password: abhishek123
    role: Admin

  - email: rahul@voltup.in
    password: rahul123
    role: Operations Head

  - email: riya@voltup.in
    password: riya123
    role: Sales Head