users:
  - email: admin@voltup.com
    password: voltup123
    role: Admin

  - email: tech@voltup.com
    password: tech123
    role: Technician

  - email: support@voltup.com
    password: support123
    role: Support

  - email: regional@voltup.com
    password: region123
    role: Regional Head

  - email: circle@voltup.com
    password: circle123
    role: Circle Head
